### ISSUE TITLE
Microsoft Defender detects application as trojan

### ISSUE THREAD

**Issue by ljcool2006** [legofanlovessayori/xpunity-sndrec32#1]
1. Download the latest release
2. Run the .exe file
The application gets blocked and detected as [Trojan:Win32/Wacatac.B!ml](https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Win32/Wacatac.B!ml&threatid=2147735505)

**Comment by legofanlovessayori** [comment]
microsofts fuck up, can't be fixed

is a false positive
